### ISSUE TITLE
Add table styling

### ISSUE THREAD

**Issue by stefanprodan** [openfaas/openfaas.github.io#10]
A table in looks like this now:

<img width="805" alt="screen shot 2018-08-01 at 17 09 17" src="https://user-images.githubusercontent.com/3797675/43526832-c7105f50-95ad-11e8-9fe0-5eff97c2c7bf.png">

We should stye it like GitHub does:

<img width="917" alt="screen shot 2018-08-01 at 17 11 37" src="https://user-images.githubusercontent.com/3797675/43526925-fd2eeb6a-95ad-11e8-88d0-04831f79609a.png">

**Comment by alexellis** [comment]
Would you be able to work on this?

**Comment by stefanprodan** [comment]
CSS is not my thing...

**Comment by ivanayov** [comment]
Derek add label: help wanted

**Comment by alexellis** [comment]
Derek add label: help wanted
