### ISSUE TITLE
broken /community link on DigitalOcean

### ISSUE THREAD

**Issue by benatkin** [openfaas/openfaas.github.io#134]
On [this DigitalOcean page](https://marketplace.digitalocean.com/apps/openfaas-kubernetes), underneath Support Details, it links to /community which returns a 404.

https://marketplace.digitalocean.com/apps/openfaas-kubernetes

**Comment by alexellis** [comment]
Could you inform DigitalOcean please?

**Comment by benatkin** [comment]
I sent it. Closing so it doesn't take up space on here. Will update here when I hear back, and if I don't, I'll message them again (set myself a reminder to check on it in a week).

**Comment by alexellis** [comment]
Thank you :+1:

I'll also send this issue over to the marketplace team.
