### ISSUE TITLE
Tweak list of templates on homepage

### ISSUE THREAD

**Issue by Waterdrips** [openfaas/openfaas.github.io#160]
We have added a few example code blocks for some functions,

We should review the examples now we have put the initial implementation in.

(#159 was the merged PR)

**Comment by Waterdrips** [comment]
https://github.com/openfaas/openfaas.github.io/pull/159#issuecomment-582521968

**Comment by alexellis** [comment]
@Waterdrips does this need closing now?

**Comment by Waterdrips** [comment]
/close 

Looks like it
