### ISSUE TITLE
Blog Tag links go to 404 page

### ISSUE THREAD

**Issue by Waterdrips** [openfaas/openfaas.github.io#161]
The "serverless" and other tags in first screenshot link to 404 page in second screenshot 
![Screenshot from 2020-02-12 08-47-36](https://user-images.githubusercontent.com/40488132/74318037-5d97dc80-4d74-11ea-8852-53d22a132395.png)

![Screenshot from 2020-02-12 08-47-50](https://user-images.githubusercontent.com/40488132/74318038-5ec90980-4d74-11ea-9530-48d2c909365d.png)

**Comment by alexellis** [comment]
As a temporary fix, how about if we disabled the hyperlinks?

**Comment by Waterdrips** [comment]
/close

this was done
