### ISSUE TITLE
Long post titles + descriptions overflow on mobile

### ISSUE THREAD

**Issue by johnmccabe** [openfaas/openfaas.github.io#21]
A picture is worth a thousand words..

<img width="400" alt="screen shot 2018-08-24 at 08 02 22" src="https://user-images.githubusercontent.com/83862/44569981-0fec7600-a774-11e8-9186-823061c3a3bf.png">

**Comment by Qfist** [comment]
Otherwise some other responsive design techniques might help.

**Comment by Qfist** [comment]
Ignore my first comment.
You simply have unresponsive header text.
H1 tag is set to 3.8 em
Simple media query to reduce it to 2rem or something similar on small screens would solve this.

**Comment by Qfist** [comment]
2rem H1:

![smallfaas](https://user-images.githubusercontent.com/2602691/44663379-a9d04f00-aa10-11e8-80a6-24b4438d03fa.png)

**Comment by johnmccabe** [comment]
Hi @Qfist theres already a PR linked above #22

**Comment by Qfist** [comment]
Hi @johnmccabe , you are right. Sorry , i was looking at blog posts. They still overflow at certain width.

**Comment by johnmccabe** [comment]
This was merged in #22

**Comment by johnmccabe** [comment]
Derek close
