### ISSUE TITLE
[Blog] OpenFaaS w/ Tilt

### ISSUE THREAD

**Issue by kevin-lindsay-1** [openfaas/openfaas.github.io#220]
Blog post showing how to set up a project for local usage with [tilt](https://tilt.dev), some of the cool things you can do with it, and some general recommendations with keeping things consistent across multiple environments.

- List requirements
- Install tilt
- Project setup
- `tilt up`
- invoke function
- `tilt down`

Future posts:

- OpenFaaS w/ Tilt: Slice-and-Dice the Stack with Nested Tiltfiles

**Comment by alexellis** [comment]
That sounds like a good layout to me. What title do you have in mind?

Does it include live rebuild/reload of the function through an fswatch?

For ideas:
https://www.locationrebel.com/blog-post-titles/
https://www.hostgator.com/blog/tips-creating-great-blog-titles/

For the overall tone/style, something that is light on formal language, without complex sentences seems to work well for our international readers.

https://www.openfaas.com/blog/serverless-nodejs/
https://blog.alexellis.io/how-i-test-openfaas-with-kubernetes/

**Comment by kevin-lindsay-1** [comment]
Some possible titles:
- [How to] Turbocharge Your [Team's] OpenFaaS Workflow with Tilt
- Turbocharge Your [Team's] OpenFaaS Functions with Tilt
- Turbocharge [Your [Team's]] Local Development with Tilt and OpenFaaS

> Does it include live rebuild/reload of the function through an fswatch?

Tilt does a full image rebuild (with cache, of course) and deployment by default, but for true live updates, it does some magic tricks to send files you watch using a path pattern, and then runs an associated command on the containers(s) while running. You can send multiple files to watch, and the order in which your live update commands should run.

I'll give those a read and see if I can internalize the tone.

**Comment by alexellis** [comment]
So how about problem/benefit in the title?

**Comment by sayjeyhi** [comment]
@alexellis @kevin-lindsay-1 I need documentation about how should I do that and came here from searching about tilt with openfaas. Is this blog post ready?

**Comment by kevin-lindsay-1** [comment]
@sayjeyhi https://github.com/openfaas/openfaas.github.io/pull/231

It's been out there for a while, nothing outstanding as far as I know.

The article is in markdown, so feel free to check it out, and there's a very simple example repo.

My patterns have only improved since the initial writing of this article, and there's plenty of secret sauce I use on a daily basis that isn't covered in that article (such as nested stacks), so if you have any questions feel free to hit me up in the OpenFaaS Slack.

**Comment by sayjeyhi** [comment]
Thanks, dear @kevin-lindsay-1. I read that article and cloned that repo, then started testing it; that is pretty cool. But I have one question. Can't we somehow do this without pushing to docker? and just watch changes, run the app using that openfaas no registry push flag?

**Comment by kevin-lindsay-1** [comment]
@sayjeyhi  You could script anything you want with Tilt, it's a fully-featured scripting language, so anything you could do through the CLI you can do via Tilt.

It's designed to work with Kubernetes, though, so using Docker is generally the pattern. A Tiltfile without docker/kubernetes could be accomplished with probably any shell scripting language or programming language of your choice.

I use it for parity between my local workflow and develop/staging/prod, so that I know that there's very little changes between them, and what changes there are, are declarative.

**Comment by alexellis** [comment]
thanks for the blog post. This is now published.
