### ISSUE TITLE
[Blog] Manage your OpenFaaS functions through GitOps principles using ArgoCD 

### ISSUE THREAD

**Issue by developer-guy** [openfaas/openfaas.github.io#222]
## What would you like to let us know?

We are planning to create a series of blog posts, in the first part of the series, we are going to talk about how we can manage OpenFaaS functions using ArgoCD locally which means the target and source Kubernetes cluster is in the same host/machine. But there is a chance available for us here because if we want to separate the target and source Kubernetes cluster that is all in a private network, we can use inlets-pro to open secure tunnels between them, so, we can install ArgoCD on a source cluster, then we add the other cluster as a target for it to deploy OpenFaaS functions to the target cluster.
* Manage your OpenFaaS functions through GitOps principles using ArgoCD  - Part 1 (everything on the same host)
* Manage your OpenFaaS functions through GitOps principles using ArgoCD  - Part 2 (between hosts in a private network)

What's wrong?

* [ ] I found a typo
* [ ] An update required to an old post
* [ ] I'm stuck with a tutorial

Let us know more below:

## Do you want to chat to us about this issue?

Head over to Slack https://slack.openfaas.io/

**Comment by developer-guy** [comment]
cc: @dentrax

**Comment by alexellis** [comment]
> Manage your OpenFaaS functions through GitOps principles using ArgoCD - Part 1 (everything on the same host)

Let's make this two separate blog posts, without the ideas being mixed?

1) Bring GitOps to your OpenFaaS functions with ArgoCD
2) Deploy your functions to the edge with ArgoCD and Inlets PRO

I am conscious that everything I've seen so far has mixed the ideas, even the diagrams and the idea of a series. Please can you keep this very clean cut. Two separate ideas, two separate blog posts. Both use ArgoCD.
