### ISSUE TITLE
Change docker command in NodeJS blog post

### ISSUE THREAD

**Issue by godspeedelbow** [openfaas/openfaas.github.io#244]
## What would you like to let us know?

* [x] An update required to an old post

I was going through https://github.com/openfaas/openfaas.github.io/blob/a14200425df7067497abdb59afbbc2745e4e7b8d/_posts/2020-12-02-serverless-nodejs.md and there's an issue with the 2nd example. Last line in `dockerfile` should be: `CMD ["node", "index.js"]` (two separate items). It wouldn't boot otherwise

**Comment by alexellis** [comment]
Hi Eekle, thanks for raising this issue

You are absolutely right and this has now been updated.

Thanks for using OpenFaaS.

Alex

**Comment by godspeedelbow** [comment]
Cheers 👍
