### ISSUE TITLE
Hamburger menu not working  on iPhone

### ISSUE THREAD

**Issue by csantanapr** [openfaas/openfaas.github.io#270]
I can't click the hamburger menu on the website using iPhone safari iOS

![image](https://user-images.githubusercontent.com/1094878/161433398-19c4a9f2-0271-44f0-9350-1b4607ff8c75.jpeg)

**Comment by alexellis** [comment]
Thanks for letting us know.

I don't have an iPhone, but if anyone can help with this, I'd appreciate it.
