### ISSUE TITLE
Blog post: September Office Hours

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas.github.io#30]
Title: September Office Hours - Multi-user OpenFaaS Cloud, Istio Service Mesh and stateless microservices

This is a recap of the community call with a video embedded and a summary of the topics covered / updates from the project with relevant links off to wherever is needed.

Author: Burton
Editor: Alex

https://www.youtube.com/watch?v=gkKpercV6FA

**Comment by alexellis** [comment]
@stefanprodan can you give us a short paragraph on your Istio work done in the video?

Something like:

"I wanted to integrate Istio with OpenFaaS because... "

Stefan Prodan, Core Contributor

**Comment by stefanprodan** [comment]
I wanted to integrate OpenFaaS with Istio to take advantage of Istio builtin security features and tracing capabilities. Some of features demoed are: mutual TLS between OpenFaaS core services and functions, Jaeger tracing for function calls, function isolation with Mixer policies.

**Comment by alexellis** [comment]
Hi folks, sorry this didn't get off the ground. I'll close and we can revisit with individual blog posts highlighting some of these areas/features like Istio or the OFC GitLab integration.
