### ISSUE TITLE
Home page when click end-users link appear error 

### ISSUE THREAD

**Issue by feifeiiiiiiiiiii** [openfaas/openfaas.github.io#32]
In OpenFaas' blog Home page, click `end-users` link  appear error, the error is `$(this.hash).offset is undefined`, screen image  as follow:

![image](https://user-images.githubusercontent.com/3310967/46011341-1d40ab80-c0f8-11e8-9d4d-d934142d3015.png)

![image](https://user-images.githubusercontent.com/3310967/46011380-39444d00-c0f8-11e8-9e55-21d53b002091.png)

**Comment by alexellis** [comment]
@johnmccabe PTAL

For now I've removed the anchor:

https://github.com/openfaas/openfaas.github.io/commit/e37c2e8f24a6f41f64d65b2871d4976597149c6a

**Comment by johnmccabe** [comment]
@alexellis I've removed the unused handler from `js/main.js` in #33
