### ISSUE TITLE
Add "Team" page

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas.github.io#39]
We should add a "Team" page which lists all of the following:

- Project Lead
- Core contributors
- GitHub organization members

For each person let's add:

- GitHub avatar (find link from GitHub)
- Full name
- GH links/button and where available one for Twitter
- 3-5 hashtags with areas of expertise (i.e. faas / faas-cli / kubernetes /  arm )

This should be a plain layout as shown on sites such as: https://www.weave.works/company/

I'd like to see 2-3 designs before moving ahead with the page.

**Comment by bartsmykla** [comment]
Derek assign: me

**Comment by alexellis** [comment]
cc @allendjal @johnmccabe

**Comment by bartsmykla** [comment]
Full page:
![image](https://user-images.githubusercontent.com/11655498/49074765-afb71580-f235-11e8-888f-060f70cec0c2.png)

**Comment by bartsmykla** [comment]
Proposition #2:
![image](https://user-images.githubusercontent.com/11655498/49074841-dbd29680-f235-11e8-9990-d141a78281b8.png)

**Comment by alexellis** [comment]
We looked at this during the team meeting today. It'd be good to see how this looks if we had a bit of text for each person. How much text would we need or like to fit in?

The team liked the circles, but I also wondered if we could combine with the outer border?

**Comment by alexellis** [comment]
Hi @bartsmykla how is the updated design going?

Thanks,

Alex

**Comment by johnmccabe** [comment]
I've raised #44 to address this, zero activity here or on any forks, it was a quick change so just got it out of the way.
