### ISSUE TITLE
Update team to be alphabetical on last name

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas.github.io#45]
We should update the team page to be listed alphabetical on last name

The headings could also be tweaked:

Core Team = Core Contributors
Members = GitHub Members

Then let's add a note to the README.md to say how to add a new person based upon the instructions from @johnmccabe in #44 

Alex

**Comment by saldistefano** [comment]
@alexellis There is a difference between the title of this issue and the description, can you confirm that you are refering to team page as I do not see a task page?

"We should update the **task** page to be listed alphabetical on last name"

Thank you,

Sal

**Comment by alexellis** [comment]
I've done a quick edit. Thanks for pointing that out.
