### ISSUE TITLE
OPENFAAS_URL in blog post results in dupe http://

### ISSUE THREAD

**Issue by oskapt** [openfaas/openfaas.github.io#57]
Usually `OPENFAAS_URL` would be a full URI, but the examples that follow include `http://admin:password@$OPENFAAS_URL/system/secrets` which would expand to `http://admin:password@http://your.gateway.com/system/secrets`, and this would fail.

PR inbound in a moment.

**Comment by alexellis** [comment]
👍 fixed in the post
