### ISSUE TITLE
Document usage

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas.github.io#7]
Hi @johnmccabe - thank you so much for putting this together

Could you document usage for local preview / PR / etc?

It would also be good to have a note on YouTube and the headers at the top of an article, plus anything else you feel is required.

Alex

**Comment by alexellis** [comment]
I'd suggest populating this data in the README file

We should also link to the new blog via the README in the faas repo and the landing page of the docs. (@viveksyngh do you want to do that bit?)

**Comment by viveksyngh** [comment]
@alexellis I have created PR to add new blog and docs site to README here https://github.com/openfaas/faas/pull/792.  I have added both in getting started section. Let me know if this looks fine or would you like me to add this somewhere else?

**Comment by alexellis** [comment]
@johnmccabe @stefanprodan is looking to be the second author to the site, please could you write up a quick list of bullets for how to contribute a post and how to stand it up locally?

**Comment by alexellis** [comment]
Appreciated!

**Comment by johnmccabe** [comment]
Derek close
