### ISSUE TITLE
Re-design site

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas.github.io#72]
I'm working with a designer to come up with a new design for the website, the low hanging fruits are:

* social sharing bar at the bottom of the screen (use font-awesome for the icons)
* centre the nav-bar
* cropping the large blue section on each page when no background image is being used

Other assorted/quick wins from the design assets before we finalise icons and copy text.

**Comment by burtonr** [comment]
Derek close

**Comment by burtonr** [comment]
Site updated with PR #102
