### ISSUE TITLE
Blog post: OpenFaaS with Kafka

### ISSUE THREAD

**Issue by martindekov** [openfaas/openfaas.github.io#76]
I think it is good to have blog post about how to subscribe your functions with kafka-connector and imply that you can implement your own invoking mechanism with the connector-sdk, because I think lots of people might benefit from OpenFaaS but not directly with HTTP.

The general layout of the blog I was thinking about is:

Talk about how OpenFaaS serves its purpose perfectly as production ready Serverless framework, but often times it is part of some bigger ecosystem of software, in which the framework may take part and often those parts don't necessary communicate to each-other using HTTP.

Tell about the kafka-connector and say it is extension of the `connector-sdk` with which you can implement your own invoking mechanism.

Then go with guide how to test it using the existing `kafka-conector` implementation with the `producer` inside the repository.

Feedback on the approach appreciated 👍

**Comment by alexellis** [comment]
Can you give bullet point headings please @martindekov ?

No need to focus on HTTP IMHO. Just a clear technical piece showing how to set up and use it.

**Comment by martindekov** [comment]
Ok here it is:

Intro: I will be showing you how to use OpenFaaS with kafka-connector on Kubernetes

OpenFaaS as piece of bigger ecosystem of software which needs to communicate with each-other

> Note: beginning like this since this is my use-case ^

* Prerequisites

Basic understanding of kubernetes and deployed OpenFaaS instance

> This might be more verbose in the Blog

* Deploy function with topic of your choice 

> Steps to deploy function with topic annotation

* Deploy kafka-connector with your configuration

> Steps to deploy the connector with your configuration

* Test it out

> Invoke function with the producer in the repo

* Next steps

Here I will mention the connector-sdk as integral part of the kafka-connector and note that you can create your own invoking mechanism.

**Comment by alexellis** [comment]
How does the Kafka-connector helm chart look now? 

@rgee0 any thoughts on the outline?

**Comment by martindekov** [comment]
I haven't deployed it with charts, I saw Ron having PR for this but haven't tested it out. Should I ?

**Comment by alexellis** [comment]
Please

**Comment by martindekov** [comment]
Ok checked the charts on Ron's PR I deployed the `kafka-connector` with charts seems to work. The producer provided by the broker deployment seems to fail invoking a function, but with your producer it works like a fine wine.

**Comment by martindekov** [comment]
I suppose the guide should deploy the connector with the helm chart and I didn't see Ron answering my comments. From functional standpoint it(helm chart deployment) works should we merge that ?
