### ISSUE TITLE
missing og:image tag on homepage

### ISSUE THREAD

**Issue by ewilde** [openfaas/openfaas.github.io#85]
It seems that we are not generating an `og:image` tag see: [linkedin post inspector](https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fwww.openfaas.com%2F) on the home page

I _think_ this means it won't generate a nice image if you link to the home page, note this is *not* an issue for blog pages e.g.  [linkedin post inspector for a blog post](https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fwww.openfaas.com%2Fblog%2Fopenfaas-cloud-gitlab%2F)

**Comment by alexellis** [comment]
cc @johnmccabe

**Comment by alexellis** [comment]
Adding this sounds good to me.

**Comment by johnmccabe** [comment]
yep sounds reasonable, should also ensure twitter and facebook header metadata tags are also getting set on the non-blog pages.

**Comment by alexellis** [comment]
At least the blog isn't too bad, but I still want to see this fixed.

`https://www.openfaas.com/blog/`

**Comment by rgee0** [comment]
Homepage fixed in #138.  The image may need swapping, however.

Is `/blog` top level requiring something more 'on brand'?

**Comment by alexellis** [comment]
Yes Richard, the same image would be ideal rather than the water. / sea-shore.

**Comment by alexellis** [comment]
Closing as resolved.
